[package]
name = "speed-light"
version = "0.1.0"
authors = ["zengzutao <zengzutao@coding.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
